CREATE TABLE TEST_PUSH_TYPE (
    ID NUMBER(22) NOT NULL,
    VALUE VARCHAR2(64) NOT NULL
)
TABLESPACE &&TS_DATA;

CREATE TABLE push (
    ID NUMBER(22) NOT NULL,
    VALUE VARCHAR2(64) NOT NULL
)
TABLESPACE TS_DATA;