- hosts: upload
  gather_facts: true
  #become: yes
  become_method: runas
  vars_files:
    - ../vars/epm.vars
  tasks:

    - name: Verify if file extension is zip
      fail:
        msg: "Package file '{{ package_name }}' not having .zip extension, failing the pipeline"
      when: package_name is not regex(".*\\.zip$")

    - name: Create timestamp
      set_fact:
        date_time: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"

    - name: Ensure package exists in upload directory
      win_stat:
        path: "{{ upload_source_path }}\\{{ package_name }}"
      register: pkg_stat

    - name: Fail if package not found
      fail:
        msg: "Package not found at {{ upload_source_path }}\\{{ package_name }}"
      when: 
        - not pkg_stat.stat.exists

    - name: Build full source file path
      set_fact:
        source_file: "{{ upload_source_path }}\\{{ package_name }}"
        artifact_name: "TestPackage_{{ date_time }}.zip"

    - name: Upload the Package to Nexus {{ENVNAME}} dir from a Win source server
      win_shell: >
        curl.exe -v -k -u {{ nexus_username }}:{{ nexus_password }}
        --upload-file "{{ source_file }}"
        "{{ nexus_np_path }}{{ ENVNAME }}/{{ artifact_name }}"
      register: upload_pkg
    
    - name: Print upload status
      debug:
        msg: "Uploaded to {{ENVNAME}} dir: {{ artifact_name }}"
