---
- name: Run Oracle SQL script on Windows server
  hosts: oracle_windows
  gather_facts: no
  tasks:
    - name: Run SQL*Plus with script
      win_shell: |
        sqlplus / as sysdba @C:\Users\oracle\Desktop\create_test_user.sql
      register: sqlplus_output

    - name: Show output
      debug:
        var: sqlplus_output.stdout
