---
- name: Run Oracle SQL script on Windows server
  hosts: oracle_windows
  gather_facts: no
  vars_files:
    - "../vars/common.var"
  tasks:

    - name: Split SQL filenames
      set_fact:
        sql_files: "{{ file_names.split(',') }}"

    - name: Copy all SQL files to the DB host
      copy:
        src: "files/sql/{{ item | trim }}"
        dest: "{{ script_path }}\\{{ item | trim }}"
      loop: "{{ sql_files }}"

    - name: "Copy sql script files to DB host inside master.sql"
      template:
        src: ../master.sql.j2
        dest: "{{ script_path }}\\master.sql"

    - name: "Build master.sql from parameters"
      template:
        src: master.sql.j2
        dest: "{{ script_path }}\\master.sql"

    - name: Run SQL*Plus with script
      win_shell: |
        sqlplus {{ db_username }}/{{ db_password }}@{{ db_host }}:{{ db_port }}/{{ db_svc }} @{{ script_path }}\{{ file_name }}
      register: sqlplus_output

    - name: Show output
      debug:
        var: sqlplus_output.stdout
