- name: Ensure version directory exists
  file:
    path: "/opt/myapp/versions/{{ version_id }}"
    state: directory
    mode: '0755'
  when: task == "deploy"

- name: Download and deploy each package with custom steps
  block:
    - name: Download package from Nexus
      get_url:
        url: "{{ nexus_path }}/{{ item }}"
        dest: "/tmp/{{ item }}"
        mode: '0644'
        force: yes
        url_username: "{{ nexus_username }}"
        url_password: "{{ nexus_password }}"
        validate_certs: no

    - name: Extract the tar.gz package
      unarchive:
        src: "/tmp/{{ item }}"
        dest: "/opt/myapp/versions/{{ version_id }}/{{ item | regex_replace('\\.tar\\.gz$', '') }}"
        remote_src: yes

    - name: Custom step for app package
      shell: "echo 'Running app post-deploy logic for {{ item }}'"
      when: item == 'app.tar.gz'

    - name: Custom step for config package
      shell: "echo 'Running config post-deploy logic for {{ item }}'"
      when: item == 'config.tar.gz'
  when: task == "deploy"
  loop: "{{ file_name.split(',') }}"
