- name: Upload multiple files to Nexus
  hosts: "{{ COMP }}"
  become: yes
  gather_facts: false
  vars_files:
    - "../vars/common.var"

  tasks:

    - name: Check if filename extension is tar.gz
      fail:
        msg: "package file '{{ item }}' does not have .tar.gz extension. Failing the pipeline."
      when: item is not regex(".*\\.tar\\.gz$")
      loop: "{{ file_name.split(',') }}"


    - name: Check if file exists in Nexus
      shell: |
        curl -I -u {{ nexus_username }}:{{ nexus_password }} {{ nexus_path }}/{{ item }}
      register: artifact_status
      ignore_errors: true
      loop: "{{ file_name.split(',') }}"
      when: task == "upload"

    - name: Fail if file already exists
      fail:
        msg: "{{ item.item }} already uploaded to Nexus"
      loop: "{{ artifact_status.results }}"
      when:
        - task == "upload"
        - item.stdout is search("200 OK")

    - name: Upload file to Nexus
      shell: |
        curl -v -u {{ nexus_username }}:{{ nexus_password }} --upload-file {{ upload_source_path_lin }}/{{ item }} {{ nexus_path }}
      when: task == "upload"
      loop: "{{ file_name.split(',') }}"

    - name: Ensure version directory exists
      file:
        path: "/opt/myapp/versions/{{ version_id }}"
        state: directory
        mode: '0755'
      when: task == "deploy"

    - name: Download package from Nexus
      get_url:
        url: "{{ nexus_path }}{{ file_name }}"
        dest: "/tmp/{{ file_name }}"
        mode: '0644'
        force: yes
        url_username: "{{ nexus_username }}"
        url_password: "{{ nexus_password }}"
        validate_certs: no
      when: task == "deploy"

    - name: Extract the tar.gz package
      unarchive:
        src: "/tmp/{{ file_name }}"
        dest: "/opt/myapp/versions/{{ version_id }}"
        remote_src: yes
      when: task == "deploy"

    - name: (Optional) List contents of the version directory
      shell: ls -l /opt/myapp/versions/{{ version_id }}
      register: lsout
      when: task == "deploy"

    - debug:
        var: lsout.stdout_lines
      when: task == "deploy"

    - name: Backup bash_profile before editing
      copy:
        src: "/home/appuser/.bash_profile"
        dest: "/home/appuser/.bash_profile.bak"
        remote_src: yes
        owner: appuser
        group: appuser
        mode: '0644'
      when: task == "deploy"

    - name: Extract previous ZZZTDS version
      shell: "grep '^export ZZZTDS=' /home/appuser/.bash_profile | tail -n 1"
      register: prev_zzzt_line
      ignore_errors: yes
      when: task == "deploy"

    - name: Remove all ZZZTDS lines (active or commented)
      lineinfile:
        path: "/home/appuser/.bash_profile"
        regexp: '^#* *export ZZZTDS=.*'
        state: absent
        owner: appuser
        group: appuser
        mode: '0644'
      when: task == "deploy"

    - name: Add previous ZZZTDS as a comment if exists
      lineinfile:
        path: "/home/appuser/.bash_profile"
        line: "# {{ prev_zzzt_line.stdout }}"
        insertafter: EOF
        state: present
      when: 
        - task == "deploy"
        - prev_zzzt_line.stdout != ""

    - name: Add current ZZZTDS line
      lineinfile:
        path: "/home/appuser/.bash_profile"
        line: 'export ZZZTDS=$PPT/ZZZTDS-{{ version_id }}'
        insertafter: EOF
        state: present
        owner: appuser
        group: appuser
        mode: '0644'
      when: task == "deploy"
