- name: Configure and install HTTPD
  hosts: your_target
  become: true
  gather_facts: false

  tasks:
    - name: Install httpd and mod_ssl
      yum:
        name:
          - httpd
          - mod_ssl
        state: present

    - name: Comment out Listen 80 in httpd.conf
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80'
        line: '#Listen 80'
        state: present

    - name: Add Listen 90 if not present
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: 'Listen 90'
        insertafter: EOF

    - name: Add <Location> block to httpd.conf
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        marker: "# {mark} Ansible Location Block"
        block: |
          <Location /GatewayService>
              pro....
              kfjkwe...
              lkdsmklv...
          </Location>

    - name: Add <VirtualHost> block to vhosts config
      blockinfile:
        path: /etc/httpd/conf.d/httpd-vhosts.conf
        marker: "# {mark} Ansible VirtualHost Block"
        block: |
          <VirtualHost *:90>
              pro....
              kfjkwe...
              lkdsmklv...
          </VirtualHost>

    - name: Restart HTTPD
      service:
        name: httpd
        state: restarted
