- name: Deploy each tar.gz package
  hosts: "{{ COMP }}"
  gather_facts: false
  vars_files:
    - "../vars/common.var"

  tasks:
    - name: Deploy each file
      include_tasks: deploy_tar_package.yml
      loop: "{{ file_name.split(',') }}"
      loop_control:
        loop_var: file
      when: task == "deploy"


